[SERIAL]
# 仮想環境では /dev/ttyS0 を使用
# 物理環境では /dev/ttyUSB0 や /dev/ttyACM0 を使用
port = /dev/ttyS0
baudrate = 9600
bytesize = 8
parity = N
stopbits = 1
timeout = 1.0
rtscts = False
dsrdtr = False
xonxoff = False

[APP]
log_level = INFO
timestamp_format = %Y-%m-%d %H:%M:%S.%f
