[SERIAL]
# Use /dev/ttyS0 in virtual environments
# In physical environments, use /dev/ttyUSB0 or /dev/ttyACM0
port = /dev/ttyS0
baudrate = 9600
bytesize = 8
parity = N
stopbits = 1
timeout = 1.0
rtscts = False
dsrdtr = False
xonxoff = False

[APP]
log_level = INFO
timestamp_format = %%Y-%%m-%%d %%H:%%M:%%S.%%f